/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Producto;
import Modelo.Sucursales;
import javax.swing.JOptionPane;

/**
 *
 * @author Newlifew
 */
public class EliminarProducto extends javax.swing.JFrame {

    /**
     * Creates new form EliminarProducto
     */
    private Sucursal sucursal;
    private int y;
    public EliminarProducto(Sucursal sucursal) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Eliminar Producto");
        this.sucursal = sucursal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        direccions = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Direccion sucursal:");

        jButton3.setText("Buscar ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Codigo", "Descripción", "Precio Unidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(direccions))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         sucursal.setVisible(true); this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int g = jTable1.getSelectedRow();
        if(g != -1)
        {
        Producto nuevo = this.sucursal.mercado.getSucursal().get(y).getProducto().get(g);
        this.sucursal.mercado.getSucursal().get(y).eliminarProducto(nuevo.getCodigo());
        mostrar();
        }
        else{JOptionPane.showMessageDialog(null,"elija un producto");}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String direccion = direccions.getText();
        if(!direccion.isEmpty())
      {
          Sucursales nuevo = this.sucursal.mercado.BuscarDireccion(direccion);
          if(nuevo != null)
          {
            
            if(!this.sucursal.mercado.getSucursal().isEmpty())
            {
              Sucursales nueva = this.sucursal.mercado.BuscarDireccion(direccion);
              if(nueva != null)
              {
                 this.y = this.sucursal.mercado.buscarSucursalint(direccion);
                
                if(!this.sucursal.mercado.getSucursal().get(y).getProducto().isEmpty())
                {
                    mostrar();
                }
                  
                }
                else{
                 JOptionPane.showMessageDialog(null,"No existe productos");}
              }
              else
             {JOptionPane.showMessageDialog(null,"No existe sucursal");}
            }
            else
            {JOptionPane.showMessageDialog(null,"No hay sucursales");}    
        }
        else
        {
          JOptionPane.showMessageDialog(null,"Hay espacios vacios");
        }
    }//GEN-LAST:event_jButton3ActionPerformed
 public void mostrar()
    {
    String [][]nuevo = new String[this.sucursal.mercado.getSucursal().get(y).getProducto().size()][4];
    for(int t=0;t<this.sucursal.mercado.getSucursal().get(y).getProducto().size();t++)
    {
       nuevo[t][0] = this.sucursal.mercado.getSucursal().get(y).getProducto().get(t).getNombre();
       nuevo[t][1] = ""+this.sucursal.mercado.getSucursal().get(y).getProducto().get(t).getCodigo();
       nuevo[t][2] = this.sucursal.mercado.getSucursal().get(y).getProducto().get(t).getDescripcion();
       nuevo[t][3] = ""+this.sucursal.mercado.getSucursal().get(y).getProducto().get(t).getPrecioUnidad();
    }
     jTable1.setModel(new javax.swing.table.DefaultTableModel( 
             nuevo, new String [] {"Nombre", "Codigo", "Descripción","Precio"}
        ));
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField direccions;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
