/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author claus
 */
public class Formulario_Registro extends javax.swing.JFrame {

    /**
     * Creates new form Formulario_Registro
     */
    public Formulario_Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Resgistro = new javax.swing.JPanel();
        JBGuardar = new javax.swing.JButton();
        JBEliminar = new javax.swing.JButton();
        JBActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TXcedula = new javax.swing.JTextField();
        TXNombre = new javax.swing.JTextField();
        TXDireccion = new javax.swing.JTextField();
        TXTelefono = new javax.swing.JTextField();
        TXEstrato = new javax.swing.JTextField();
        TXEstado = new javax.swing.JTextField();
        JBBuscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TXApellidos = new javax.swing.JTextField();
        Diezmo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TXCedulaC = new javax.swing.JTextField();
        TXDiezmo = new javax.swing.JTextField();
        JBConsultar = new javax.swing.JButton();
        JBPagar = new javax.swing.JButton();
        JBTotal = new javax.swing.JButton();
        Rp = new javax.swing.JScrollPane();
        RespTA = new javax.swing.JTextArea();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Parroquia PIO XX");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Resgistro.setBackground(new java.awt.Color(0, 0, 0));
        Resgistro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Regsitro Feligrés")));
        Resgistro.setForeground(new java.awt.Color(255, 153, 204));

        JBGuardar.setText("Guardar");

        JBEliminar.setText("Eliminar");
        JBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEliminarActionPerformed(evt);
            }
        });

        JBActualizar.setText("Actualizar");

        jLabel1.setText("Cédula *");

        jLabel2.setText("Nombre*");

        jLabel3.setText("Direccion*");

        jLabel4.setText("Teléfono*");

        jLabel5.setText("Estrato*");

        jLabel6.setText("Estado*");

        TXcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXcedulaActionPerformed(evt);
            }
        });

        TXNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXNombreActionPerformed(evt);
            }
        });

        TXDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXDireccionActionPerformed(evt);
            }
        });

        TXTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTelefonoActionPerformed(evt);
            }
        });

        JBBuscar.setText("Buscar");
        JBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBBuscarActionPerformed(evt);
            }
        });

        jLabel9.setText("apellidos");

        javax.swing.GroupLayout ResgistroLayout = new javax.swing.GroupLayout(Resgistro);
        Resgistro.setLayout(ResgistroLayout);
        ResgistroLayout.setHorizontalGroup(
            ResgistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResgistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ResgistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ResgistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(ResgistroLayout.createSequentialGroup()
                            .addGroup(ResgistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGroup(ResgistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(ResgistroLayout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addGroup(ResgistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TXcedula)
                                        .addComponent(TXNombre)
                                        .addComponent(TXTelefono)
                                        .addComponent(TXEstrato)
                                        .addComponent(TXEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                                .addGroup(ResgistroLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TXDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ResgistroLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(TXApellidos))))
                        .addGroup(ResgistroLayout.createSequentialGroup()
                            .addComponent(JBGuardar)
                            .addGap(18, 18, 18)
                            .addComponent(JBEliminar))
                        .addGroup(ResgistroLayout.createSequentialGroup()
                            .addComponent(JBActualizar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JBBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                    .addComponent(jLabel9))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        ResgistroLayout.setVerticalGroup(
            ResgistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResgistroLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ResgistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ResgistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ResgistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(ResgistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ResgistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TXEstrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ResgistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ResgistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(ResgistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBGuardar)
                    .addComponent(JBEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ResgistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBActualizar)
                    .addComponent(JBBuscar))
                .addGap(26, 26, 26))
        );

        getContentPane().add(Resgistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 380));

        Diezmo.setBackground(new java.awt.Color(0, 0, 0));
        Diezmo.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Diezmo"));

        jLabel7.setText("Cédula*");

        jLabel8.setText("Valor Diezmo");

        JBConsultar.setText("Consultar");
        JBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBConsultarActionPerformed(evt);
            }
        });

        JBPagar.setText("Pagar");
        JBPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPagarActionPerformed(evt);
            }
        });

        JBTotal.setText("Totalizar");
        JBTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DiezmoLayout = new javax.swing.GroupLayout(Diezmo);
        Diezmo.setLayout(DiezmoLayout);
        DiezmoLayout.setHorizontalGroup(
            DiezmoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiezmoLayout.createSequentialGroup()
                .addGroup(DiezmoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DiezmoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DiezmoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DiezmoLayout.createSequentialGroup()
                                .addGroup(DiezmoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(44, 44, 44)
                                .addGroup(DiezmoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TXCedulaC)
                                    .addComponent(TXDiezmo, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                            .addGroup(DiezmoLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(JBConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(JBPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(DiezmoLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(JBTotal)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        DiezmoLayout.setVerticalGroup(
            DiezmoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiezmoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(DiezmoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TXCedulaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DiezmoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TXDiezmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(DiezmoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBConsultar)
                    .addComponent(JBPagar))
                .addGap(18, 18, 18)
                .addComponent(JBTotal)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(Diezmo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        RespTA.setBackground(new java.awt.Color(0, 0, 0));
        RespTA.setColumns(20);
        RespTA.setRows(5);
        RespTA.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));
        Rp.setViewportView(RespTA);

        getContentPane().add(Rp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 297, 114));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 640, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBEliminarActionPerformed

    private void TXcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXcedulaActionPerformed

    private void TXNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXNombreActionPerformed

    private void TXDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXDireccionActionPerformed

    private void TXTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTelefonoActionPerformed

    private void JBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBBuscarActionPerformed

    private void JBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBConsultarActionPerformed

    private void JBPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBPagarActionPerformed

    private void JBTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBTotalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Diezmo;
    private javax.swing.JLabel Fondo;
    public javax.swing.JButton JBActualizar;
    public javax.swing.JButton JBBuscar;
    public javax.swing.JButton JBConsultar;
    public javax.swing.JButton JBEliminar;
    public javax.swing.JButton JBGuardar;
    public javax.swing.JButton JBPagar;
    public javax.swing.JButton JBTotal;
    public javax.swing.JPanel Resgistro;
    public javax.swing.JTextArea RespTA;
    private javax.swing.JScrollPane Rp;
    public javax.swing.JTextField TXApellidos;
    public javax.swing.JTextField TXCedulaC;
    public javax.swing.JTextField TXDiezmo;
    public javax.swing.JTextField TXDireccion;
    public javax.swing.JTextField TXEstado;
    public javax.swing.JTextField TXEstrato;
    public javax.swing.JTextField TXNombre;
    public javax.swing.JTextField TXTelefono;
    public javax.swing.JTextField TXcedula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
